#import "./DesktopParts.gql"
mutation DesktopUpdate ($id: Int!, $title: String, $description: String, $urls: [String!]) {
  DesktopUpdate (id: $id, title: $title, description: $description, urls: $urls) {
    ...DesktopParts
  }
}
