#import "./DesktopParts.gql"
query DesktopList($offset: Int!, $first: Int!, $orderBy: [DesktopsOrderBy!]) {
  desktops(offset: $offset, first: $first, orderBy: $orderBy) {
    nodes {
      ...DesktopParts
    }
  }
}
