#import "./DesktopParts.gql"
mutation DesktopCreate (
  $title: String!
  $description: String
  $urls: [String!]!
) {
  DesktopCreate (description: $description, title: $title, urls: $urls) {
    ...DesktopParts
  }
}
