#import "./DesktopParts.gql"
mutation updateDesktop (
  $id: UUID!
  $title: String
  $description: String
  $urls: [Url!]
) {
  updateDesktop (input: {
    id: $id
    patch: {
      title: $title
      description: $description
      urls: $urls
    }
  }) {
    desktop {
      ...DesktopParts
    }
  }
}
