#import "./DesktopParts.gql"
mutation createDesktop(
  $title: String!
  $description: String
  $urls: [Url!]!
) {
  createDesktop(
    input: {
      desktop: { description: $description, title: $title, urls: $urls }
    }
  ) {
    desktop {
      ...DesktopParts
    }
  }
}
