type Desktop {
  id: Int!
  title: String!
  urls: [String!]!
  description: String
  created_at: String!
  updated_at: String!
}

type Query {
  Desktop: [Desktop]
}

type Mutation {
  DesktopCreate(title: String!, description: String, urls: [String!]!): Desktop
  DesktopUpdate(id: Int!, title: String, description: String, urls: [String!]): Desktop
  DesktopDelete(id: Int!): Int!
}

type Subscription {
  DesktopCreated: Desktop
  DesktopUpdated: Desktop
  DesktopDeleted: Int!
}
